use test

SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO

CREATE OR ALTER PROCEDURE [dbo].[INIT_FACT_AVERAGE]

AS
BEGIN

SET NOCOUNT ON;
SET XACT_ABORT ON;

------------------------------------------------------------------------------------
-- Bắt đầu Transactionxd'
BEGIN TRAN;
BEGIN TRY;

IF EXISTS(SELECT * FROM sys.tables WHERE SCHEMA_NAME(schema_id) LIKE 'dbo' AND name like 'FACT_AVERAGE')
   DROP TABLE test.dbo.FACT_AVERAGE

CREATE TABLE test.dbo.FACT_AVERAGE (
    USER_ID                      INT,
    QUESTION_ID                  INT,
    QUESTION_TYPE                NVARCHAR(50),
    GROUP_NAME_KEY               INT,
    TRACK_NAME_KEY               INT,
    SUBTRACKNAME_KEY             INT,
    NUM_PLAYERS                  INT,
    QUESTION_SET_ID              INT,
    AVERAGE_SCORE                DECIMAL(5,2),
)

ALTER TABLE dbo.FACT_AVERAGE
ADD CONSTRAINT FK_AVERAGE_GROUP_NAME_KEY FOREIGN KEY (GROUP_NAME_KEY) REFERENCES DIM_GROUP_NAME(GROUP_NAME_KEY);
ALTER TABLE dbo.FACT_AVERAGE
ADD CONSTRAINT FK_AVERAGE_TRACK_NAME_KEY FOREIGN KEY (TRACK_NAME_KEY) REFERENCES DIM_TRACKNAME(TRACKNAME_KEY);
ALTER TABLE dbo.FACT_AVERAGE
ADD CONSTRAINT FK_AVERAGE_SUBTRACK_NAME_KEY FOREIGN KEY (SUBTRACKNAME_KEY) REFERENCES DIM_SUB_TRACKNAME(SUBTRACKNAME_KEY);



-- COMMIT HANDLE DATA
COMMIT
RETURN 0
END TRY
BEGIN CATCH
	ROLLBACK
	DECLARE @ERRORMESSAGE NVARCHAR(2000)
	SELECT @ERRORMESSAGE = 'ERROR: ' + ERROR_MESSAGE()
	RAISERROR(@ERRORMESSAGE, 16, 1)
END CATCH

-- Kết thúc Transaction
------------------------------------------------------------------------------------
END

EXEC [dbo].[INIT_FACT_AVERAGE]
GO
