USE test
GO
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO

CREATE OR ALTER PROCEDURE [dbo].[INIT_FACT_POPULARITY_IN_YEAR]

AS
BEGIN

SET NOCOUNT ON;
SET XACT_ABORT ON;
------------------------------------------------------------------------------------
-- Bat dau Transaction
BEGIN TRAN;
BEGIN TRY;

IF EXISTS(SELECT * FROM sys.tables WHERE SCHEMA_NAME(schema_id) LIKE 'dbo' AND name like 'FACT_POPULARITY_IN_YEAR')
   DROP TABLE dbo.FACT_POPULARITY_IN_YEAR

CREATE TABLE dbo.FACT_POPULARITY_IN_YEAR (
	DATE_KEY                     BIGINT,
    GROUP_NAME_KEY               INT,
    GROUP_NAME_LABEL             NVARCHAR(50),
    TRACK_NAME_KEY               INT,
    TRACK_NAME_LABEL             NVARCHAR(50),
    SUBTRACKNAME_KEY             INT,
    SUBTRACKNAME_LABEL           NVARCHAR(50),
    COUNT                        INT
)
ALTER TABLE dbo.FACT_POPULARITY_IN_YEAR
ADD CONSTRAINT FK_DATE_KEY_YEARLY FOREIGN KEY (DATE_KEY) REFERENCES DIM_DATE(DATE_KEY);
ALTER TABLE dbo.FACT_POPULARITY_IN_YEAR
ADD CONSTRAINT FK_GROUP_NAME_KEY_YEARLY FOREIGN KEY (GROUP_NAME_KEY) REFERENCES DIM_GROUP_NAME(GROUP_NAME_KEY);
ALTER TABLE dbo.FACT_POPULARITY_IN_YEAR
ADD CONSTRAINT FK_TRACK_NAME_KEY_YEARLY FOREIGN KEY (TRACK_NAME_KEY) REFERENCES DIM_TRACKNAME(TRACKNAME_KEY);
ALTER TABLE dbo.FACT_POPULARITY_IN_YEAR
ADD CONSTRAINT FK_SUBTRACK_NAME_KEY_YEARLY FOREIGN KEY (SUBTRACKNAME_KEY) REFERENCES DIM_SUB_TRACKNAME(SUBTRACKNAME_KEY);

-- COMMIT HANDLE DATA
COMMIT
RETURN 0
END TRY
BEGIN CATCH
	ROLLBACK
	DECLARE @ERRORMESSAGE NVARCHAR(2000)
	SELECT @ERRORMESSAGE = 'ERROR: ' + ERROR_MESSAGE()
	RAISERROR(@ERRORMESSAGE, 16, 1)

END CATCH

-- Ket thúc Transaction
------------------------------------------------------------------------------------
END

EXEC [dbo].[INIT_FACT_POPULARITY_IN_YEAR]
GO


-- drop PROCEDURE [dbo].[SP_INIT_FACT_SALES_MONTHLY]
-- drop TABLE FACT_SALES_MONTHLY
