USE test
GO

SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO

CREATE OR ALTER PROCEDURE [dbo].[FLOAD_DIM_OUTCOME]
AS
BEGIN

SET NOCOUNT ON
SET XACT_ABORT ON
SET IDENTITY_INSERT test.dbo.DIM_OUTCOME OFF

BEGIN TRAN
BEGIN TRY
    TRUNCATE TABLE test.dbo.DIM_OUTCOME

    INSERT INTO test.dbo.DIM_OUTCOME(OUTCOME_ID, OUTCOME_FIELD, OUTCOME_LABEL, SCORE)
    SELECT DISTINCT
    id,
    field,
    label,
    (CASE
        WHEN CATEGORY.label = 'correct' THEN 10
        WHEN CATEGORY.label = 'incorrect' THEN 0
        WHEN CATEGORY.label = 'skipped' THEN 5
        WHEN CATEGORY.label = 'timeout' THEN 1
    END) AS SCORE
    FROM STG.CATEGORY
    WHERE field = 'outcome'

COMMIT
RETURN 0
END TRY
BEGIN CATCH
    ROLLBACK
    DECLARE @errormessage NVARCHAR(2000)
    SELECT @errormessage = 'ERROR ' + ERROR_MESSAGE()
    RAISERROR(@errormessage, 16, 1)
END CATCH

END
GO

EXEC [dbo].[FLOAD_DIM_OUTCOME]
GO

