USE test
GO

SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO

CREATE OR ALTER PROCEDURE [dbo].[FLOAD_DIM_DATE]

AS
BEGIN


SET NOCOUNT ON
SET XACT_ABORT ON
--SET IDENTITY_INSERT test.dbo.DIM_DATE ON

BEGIN TRAN;
BEGIN TRY;


	TRUNCATE TABLE test.dbo.DIM_DATE;

	DECLARE @CURRENT_DATE DATE = '1900-01-01'
	/***----------------------------------------------------------------------------------***/
	-- INSERT DIM_DATE
	WHILE @CURRENT_DATE <= '2100-12-31'
	BEGIN


		INSERT INTO test.dbo.DIM_DATE(DATE_KEY, DATE,DAY,DAY_OF_WEEK,DAY_OF_WEEK_NUMBER ,MONTH,MONTH_NUMBER,QUARTER,
		QUARTER_NUMBER,YEAR,DAYS_IN_MONTH, DAYS_IN_QUARTER, DAYS_IN_YEAR, FIRST_DATE_OF_MONTH, LAST_DATE_OF_MONTH,FIRST_DATE_OF_QUARTER, LAST_DATE_OF_QUARTER, FIRST_DATE_OF_YEAR, LAST_DATE_OF_YEAR)
		SELECT

		DATE_KEY = YEAR(@CURRENT_DATE) * 10000 + MONTH(@CURRENT_DATE) *100 + DAY(@CURRENT_DATE),
		DATE=@CURRENT_DATE,
		[DAY]=DAY(@CURRENT_DATE),
		DAY_OF_WEEK = DATENAME(DW, @CURRENT_DATE),
		DAY_OF_WEEK_NUMBER =  DATEPART(DW, @CURRENT_DATE),
		MONTH=DATENAME(MM, @CURRENT_DATE),
		MONTH_NUMBER = MONTH(@CURRENT_DATE),
		QUARTER=CASE
				WHEN DATENAME(QQ, @CURRENT_DATE) = 1 THEN 'I'
				WHEN DATENAME(QQ, @CURRENT_DATE) = 2 THEN 'II'
				WHEN DATENAME(QQ, @CURRENT_DATE) = 3 THEN 'III'
				WHEN DATENAME(QQ, @CURRENT_DATE) = 4 THEN 'IV'
		END,
		QUARTER_NUMBER=DATEPART(Q, @CURRENT_DATE),
		--
		YEAR=YEAR(@CURRENT_DATE),
		--
		DAYS_IN_MONTH = DAY(EOMONTH(@CURRENT_DATE)),
		DAYS_IN_QUARTER= datediff(dd, dateadd(qq,datediff(qq,0, @CURRENT_DATE),0),dateadd(qq, datediff(qq,0,@CURRENT_DATE) + 1,0)),
		DAYS_IN_YEAR = DATEDIFF(day,  cast(YEAR(@CURRENT_DATE) as char(4)),  cast(YEAR(@CURRENT_DATE)+1 as char(4))),
		--
		FIRST_DATE_OF_MONTH = DATEFROMPARTS(YEAR(@CURRENT_DATE),MONTH(@CURRENT_DATE),1),
		LAST_DATE_OF_MONTH = EOMONTH(@CURRENT_DATE),
		--
		FIRST_DATE_OF_QUARTER= DATEADD(q, DATEDIFF(q, 0, @CURRENT_DATE), 0),
		LAST_DATE_OF_QUARTER = DATEADD (dd, -1, DATEADD(qq, DATEDIFF(qq, 0, @CURRENT_DATE) +1, 0)),
		--
		FIRST_DATE_OF_YEAR =DATEADD(yy, DATEDIFF(yy, 0, @CURRENT_DATE), 0),
		LAST_DATE_OF_YEAR = DATEADD(yy, DATEDIFF(yy, 0, @CURRENT_DATE) + 1, -1)

		SET @CURRENT_DATE = DATEADD(DAY, 1, @CURRENT_DATE)

		END

COMMIT
RETURN 0
END TRY
BEGIN CATCH
    ROLLBACK
    DECLARE @errormessage NVARCHAR(2000)
    SELECT @errormessage = 'ERROR ' + ERROR_MESSAGE()
    RAISERROR(@errormessage, 16, 1)
END CATCH

END

-- EXEC sp_configure 'clr enabled', 1;
-- RECONFIGURE;
-- GO

EXEC [dbo].[FLOAD_DIM_DATE]
GO


-- drop PROCEDURE [dbo].[SP_FLOAD_DIM_DATE]

-- select * from DIM_DATE
