USE test
GO

SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO

CREATE OR ALTER PROCEDURE [dbo].[INIT_DIM_OUTCOME]
AS
BEGIN

SET NOCOUNT ON;
SET XACT_ABORT ON;

-----------------------------------------------------------------------------

-- Transaction begin here

BEGIN TRAN;
BEGIN TRY;


IF EXISTS(SELECT * FROM sys.tables WHERE SCHEMA_NAME(schema_id) LIKE 'dbo' AND name like 'DIM_OUTCOME')
   DROP TABLE test.dbo.DIM_OUTCOME

CREATE TABLE test.dbo.DIM_OUTCOME (
	OUTCOME_KEY      INT IDENTITY(1,1) NOT NULL PRIMARY KEY,
    OUTCOME_ID       INT,
    OUTCOME_FIELD    NVARCHAR(50),
    OUTCOME_LABEL    NVARCHAR(50),
	SCORE			 INT
);

COMMIT
RETURN 0
END TRY
BEGIN CATCH
	ROLLBACK
	DECLARE @ERRORMESSAGE NVARCHAR(2000)
	SELECT @ERRORMESSAGE = 'ERROR: ' + ERROR_MESSAGE()
	RAISERROR(@ERRORMESSAGE, 16, 1)
END CATCH

-- Transaction end here

END


EXECUTE [dbo].[INIT_DIM_OUTCOME]
GO
