USE test
GO

SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO

CREATE OR ALTER PROCEDURE [dbo].[INIT_DIM_GAMETYPE]
AS
BEGIN

SET NOCOUNT ON;
SET XACT_ABORT ON;

-----------------------------------------------------------------------------

-- Transaction begin here

BEGIN TRAN;
BEGIN TRY;

IF EXISTS(SELECT * FROM sys.tables WHERE SCHEMA_NAME(schema_id) LIKE 'dbo' AND name like 'DIM_GAMETYPE')
   DROP TABLE test.dbo.DIM_GAMETYPE

CREATE TABLE test.dbo.DIM_GAMETYPE (
	GAMETYPE_KEY      INT IDENTITY(1,1) NOT NULL PRIMARY KEY,
    GAMETYPE_ID       INT,
    GAMETYPE_FIELD    NVARCHAR(50),
    GAMETYPE_LABEL    NVARCHAR(50)
);

COMMIT
RETURN 0
END TRY
BEGIN CATCH
	ROLLBACK
	DECLARE @ERRORMESSAGE NVARCHAR(2000)
	SELECT @ERRORMESSAGE = 'ERROR: ' + ERROR_MESSAGE()
	RAISERROR(@ERRORMESSAGE, 16, 1)
END CATCH

-- Transaction end here

END


EXECUTE [dbo].[INIT_DIM_GAMETYPE]
GO
