USE test
GO

SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO

CREATE OR ALTER PROCEDURE [dbo].[INIT_DIM_DATE]
AS
BEGIN

SET NOCOUNT ON;
SET XACT_ABORT ON;

-----------------------------------------------------------------------------

-- Transaction begin here

BEGIN TRAN;
BEGIN TRY;


IF EXISTS(SELECT * FROM sys.tables WHERE SCHEMA_NAME(schema_id) LIKE 'dbo' AND name like 'DIM_DATE')
   DROP TABLE test.dbo.DIM_DATE

CREATE TABLE test.dbo.DIM_DATE (
	DATE_KEY BIGINT NOT NULL PRIMARY KEY,
	DATE DATE NOT NULL UNIQUE,
    DAY TINYINT,
    DAY_OF_WEEK NVARCHAR(20),
    DAY_OF_WEEK_NUMBER INT,
    MONTH NVARCHAR(20),
    MONTH_NUMBER INT,
    QUARTER NVARCHAR(20),
    QUARTER_NUMBER INT,
    YEAR INT,
    DAYS_IN_MONTH INT,
    DAYS_IN_QUARTER INT,
    DAYS_IN_YEAR INT,
    FIRST_DATE_OF_MONTH DATE,
    LAST_DATE_OF_MONTH DATE,
    FIRST_DATE_OF_QUARTER DATE,
    LAST_DATE_OF_QUARTER DATE,
    FIRST_DATE_OF_YEAR DATE,
    LAST_DATE_OF_YEAR DATE,
)

COMMIT
RETURN 0
END TRY
BEGIN CATCH
	ROLLBACK
	DECLARE @ERRORMESSAGE NVARCHAR(2000)
	SELECT @ERRORMESSAGE = 'ERROR: ' + ERROR_MESSAGE()
	RAISERROR(@ERRORMESSAGE, 16, 1)
END CATCH

-- Transaction end here

END


EXECUTE [dbo].[INIT_DIM_DATE]
GO

-- drop table dim_date
select * from DIM_DATE
